all:

makedmg:
	rm -f RestartPCKeyboardHack.dmg
	hdiutil create -nospotlight RestartPCKeyboardHack.dmg -srcfolder RestartPCKeyboardHack.app
	rm -f ShowInstalledAppsVersion.dmg
	hdiutil create -nospotlight ShowInstalledAppsVersion.dmg -srcfolder ShowInstalledAppsVersion.app
